### ISSUE TITLE
Incompatibility with Caelus and Curious Elytra

### ISSUE THREAD

**Issue by thicc-penguin** [endorh/aerobaticelytra#1]
Details:
	Mod File: aerobaticelytra-1.16.5-1.0.0.jar
	Failure message: Mod aerobaticelytra only supports caelus 
		Currently, caelus is 1.16.5-2.1.3.2
	Mod Version: 1.0.0
	Mod Issue URL: https://github.com/endorh/aerobatic-elytra/issues
	Exception message: MISSING EXCEPTION MESSAGE

Details:
	Mod File: aerobaticelytra-1.16.5-1.0.0.jar
	Failure message: Mod aerobaticelytra only supports curiouselytra 
		Currently, curiouselytra is 1.16.5-4.0.2.4
	Mod Version: 1.0.0
	Mod Issue URL: https://github.com/endorh/aerobatic-elytra/issues
	Exception message: MISSING EXCEPTION MESSAGE

The mod seems to understand that Caelus and Curious Elytra exist but might be tuned for the wrong versions. We are using the most recent versions for 1.16.5, the mod loads perfectly without both of these.

**Comment by endorh** [comment]
Yes, the mod declares an optional dependency on both Caelus and Curios, in order to support some compatibility features.

As you have suggested, the mod seems to be tuned for the wrong versions (or no versions at all, which fails the same).

This should be a simple fix, so I'll work on it asap tomorrow.

Thanks for reporting the issue.

**Comment by thicc-penguin** [comment]
Thanks a bunch! Just of note, when using the included Curios datapack, it doesn't allow me to fly using the elytras despite being in my curio slot. I added a datapack that allowed regular vanilla Elytras to be equipped as back items and I couldn't do that either so I think the functionality is tied to Curious Elytras. 

I think once it is allowed to be compatible with Curious Elytras it should work seamlessly, but I will do extensive testing! Love the mod.

**Comment by endorh** [comment]
It's true that for vanilla Elytras you'd need Curious Elytra for it to work, but it's weird it doesn't work with the bundled datapack for Aerobatic Elytras. I'll have to do some testing.

The incompatibility is now fixed and should be available in Curse Forge soon.
The problem was I had done my tests for 1.16 with Forge 36.1.0, but Forge 36.2.+ requires optional dependencies to specify a version range.

Thanks for the involvement and feedback.

**Comment by thicc-penguin** [comment]
Hi, just as a follow-up. I did some extensive testing with a heavy modpack of 295 mods, it works perfectly. The only thing that doesn't work is hiding the elytra using Curios' hide cosmetic option, but otherwise it seems quite stable and very performance friendly, save for some players figuring out how to achieve FTL and nuking the server ram, but that's because of our added mods and their speed enhancing properties (ProjectE) so it isn't an issue. More of a player problem when they have the desire to cosplay a bullet.

The cosmetic thing should be very low on the laundry list, congrats on making such a great release! Thank you so much for your hard work and amazing mod. This can be closed now since the initial issue has been resolved! Happy holidays.

**Comment by endorh** [comment]
Thanks for the follow-up. That's an impressive testing, I hope you reach the 300 milestone soon 👏

I've never known Curios had a cosmetic hide option. The reason it doesn't work is because I do my own rendering of the elytra when I detect a player has it equipped as a Curio. If I can find how to detect when the slot is hidden I'll fix that too, but I haven't found any documentation about it so far. As you say, it's quite low on the laundry list.

I agree it's rather unfortunate Minecraft can't handle higher speeds better, but it'd take a lot of effort to optimize world-loading performance to the point where players could move at speeds of several chunks per second. Hopefully one day Distant Horizons will support server-side loading of *horizon chunks* which should make the flying experience a lot better.

Thank you for your kind words. This release has taken me several months to reach, so I'm glad it's gone well. I now understand why many people prefer to do pre-releases instead xD. Happy holidays to you too 😄

**Comment by endorh** [comment]
> Thanks a bunch! Just of note, when using the included Curios datapack, it doesn't allow me to fly using the elytras despite being in my curio slot. I added a datapack that allowed regular vanilla Elytras to be equipped as back items and I couldn't do that either so I think the functionality is tied to Curious Elytras.

Btw, this is actually tied to the Caelus API, which rewrites the hardcoded condition for players to fly with Elytra. I'll document it in the wiki.
