### ISSUE TITLE
`NoClassDefFoundError` crash on server side

### ISSUE THREAD

**Issue by ctest245** [endorh/aerobaticelytra#2]
Hi, I tested this for a large modpack we have in our group and it was fine in single player, but upon uploading it to our server we were met with this error and the server refused to start.

This is the pastebin:
https://pastebin.com/azaeXFKa

**Comment by endorh** [comment]
Hi, thanks for the report. ^^

It's taken me a while, but I've been able to reproduce it.
I'll fix it as soon as I have the time to find the exact cause, which should be later today.

**Comment by endorh** [comment]
The issue turned out to be in one of my dependency mods, [LazuLib](https://github.com/endorh/lazulib).
I've fixed it in v1.0.1 which is already available at [Curse Forge](https://www.curseforge.com/minecraft/mc-mods/lazulib/files).

To be honest, I thought I'd fixed this same issue months ago, but it seems I was mistaken.
I'm sorry for the trouble. It's weird I didn't encounter it until now.

I've also updated [Flight Core](https://www.curseforge.com/minecraft/mc-mods/flight-core/files) to suppress the mixin warnings that were present only in the server side, but you don't really need to update it.

Please check if the fix works for you if you have the time.

**Comment by ctest245** [comment]
Hey, I can make a connection to the server but this error pops up: 
![image](https://user-images.githubusercontent.com/122270332/211684423-0bce9f0c-0b3e-473f-8e2e-3919d493b19f.png)

here is a snippet of the latest.log that seems to be relevant to the error.
https://pastebin.com/9DH1V7qi

[latest.log](https://github.com/endorh/aerobatic-elytra/files/10387581/latest.log)

This is the full latest log. 

After removing flight core 1.0.1, aerobatic elytra 1.1.0, aerobatic elytra jetpack 1.0.0, lazulib 1.0.1, and simpleconfig 1.0.0 from the server and client I was finally able to log in.

**Comment by endorh** [comment]
Found it, once again in LazuLib. A new fix will be uploaded soon in v1.0.2.

**Comment by endorh** [comment]
The fix should already be available at [Curse Forge](https://www.curseforge.com/minecraft/mc-mods/lazulib/files).

Please confirm if it works now for you, if you have the time.

**Comment by ctest245** [comment]
Will check tomorrow! Thank you so much for your help. Do you have a patreon or a way to support you? I really love this mod in our single player world.

**Comment by ctest245** [comment]
just checked, it's working perfectly fine now! Running around 296 mods on 1.16.5 very smoothly. Thank you for the quick response! You can close this issue 😄

**Comment by endorh** [comment]
Sorry for the delay. I'm glad it's finally working for you. That's a big modpack. 😆

I'm quite surprised these two bugs weren't found earlier. I have no idea how it was able to work on 1.16 sometimes before the fixes.

**Comment by endorh** [comment]
> Do you have a patreon or a way to support you?

At the moment, I only have a Discord server, where I post updates about my projects, but your words encourage me to create a patreon in the future. Thank you 😄
